name: Build
on:
  push:
    branches:
      - main
  pull_request:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - run: pip3 install bikeshed jinja2
      - name: Update Bikeshed
        run: bikeshed update
      - name: Compile
        run: |
          set -e
          for file in ./csswg-drafts/**/*.bs; do
            bikeshed -f spec "$file" "${file%.bs}.html"
          done
      - name: Fix directory defaults
        # The default pages for directories are assumed to be Overview.html, but
        # that doesn't work for Github Pages. So we copy them as index.html.
        run: |
          set -e
          for file in ./csswg-drafts/**/Overview.html; do
            cp "$file" "$(dirname "$file")/index.html"
          done
      - name: Build index
        run: python ./build-index.py
      - run: |
          mkdir output
          cp test-setup/templates/index.html output/index.html
          cp -r csswg-drafts output/test
      - run: rm -rf ./output/test/.git{,attributes,ignore}
      - name: Build redirects to the official mirror
        run: |
          # For every folder in ./output/test that has an index.html (except for
          # ./output/test itself), we build a redirect in ./output
          set -e
          for index in ./output/test/*/index.html; do
            folder_name="$(basename "$(dirname "$index")")"
            python ./test-setup/redirect.py "$folder_name"
          done
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          path: ./output
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: ".github"
          publish_dir: ./output
