name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Install Bikeshed
        run: pipx install bikeshed && bikeshed update
      - name: Configure Bikeshed spec data
        run: pipenv run python ./configure-spec-data.py
      - run: |
          cp -r csswg-drafts output
      - name: Compile
        run: |
          set -e
          for file in ./output/**/*.bs; do
            pipenv run bikeshed -f spec "$file" "${file%.bs}.html"
          done
      - name: Fix directory defaults
        # The default pages for directories are assumed to be Overview.html, but
        # that doesn't work for Github Pages. So we copy them as index.html.
        run: |
          set -e
          for file in ./output/**/Overview.html; do
            cp "$file" "$(dirname "$file")/index.html"
          done
      - name: Build index
        run: pipenv run python ./build-index.py
      - run: rm -rf ./output/.git{,attributes,ignore}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: ".github"
          publish_dir: ./output
